
services:

      la.symfony-ext.validator:
          class: SymfonyExtBundle\Validator\Validator
          arguments: ['@service_container']
          public: true

      la.symfony-ext.entity-properties-extractor.data:
          class: SymfonyExtBundle\EntityPropertiesExtractor\EntityPropertiesExtractor
          arguments: ['%serializer%','@service_container','@security.token_storage']
          public: true

      la.symfony-ext.entity-saver:
          class: SymfonyExtBundle\EntitySaver\EntitySaver
          arguments: ['@service_container']
          public: true
