
services:

      la.symfony-ext.validator:
          class: SymfonyExtBundle\Validator\Validator
          arguments: ['@service_container']
          public: true

      la.symfony-ext.entity-properties-extractor.data:
          class: SymfonyExtBundle\EntityPropertiesExtractor\EntityPropertiesExtractor
          arguments: ['%extract-options%','%serializer%']
          public: true

      la.symfony-ext.entity-saver:
          class: SymfonyExtBundle\EntitySaver\EntitySaver
          arguments: ['%saver-options%','@service_container']
          public: true
